### ISSUE TITLE
[UWP] Using the navigation buttons on a mouse while the cursor is over a toucheffect control will throw a null reference exception

### ISSUE THREAD

**Issue by MitchBomcanhao** [AndreiMisiukevich/TouchEffect#19]
On UWP, you can have navigation buttons on your mouse.
This means that while you press them, it'll trigger the pressed events, which will navigate to a different page but also attempt to do things like animate the background color of the affected control.
However, as the app has since navigated to a different page, the control it is trying to act upon no longer exists and a null reference exception is thrown at

TouchVisualManager.cs line 195
```
 new Animation{
                {0, 1,  new Animation(v => sender.Control.BackgroundColor = new Color(v, sender.Control.BackgroundColor.G, sender.Control.BackgroundColor.B, sender.Control.BackgroundColor.A), sender.Control.BackgroundColor.R, color.R) },
                {0, 1,  new Animation(v => sender.Control.BackgroundColor = new Color(sender.Control.BackgroundColor.R, v, sender.Control.BackgroundColor.B, sender.Control.BackgroundColor.A), sender.Control.BackgroundColor.G, color.G) },
                {0, 1,  new Animation(v => sender.Control.BackgroundColor = new Color(sender.Control.BackgroundColor.R, sender.Control.BackgroundColor.G, v, sender.Control.BackgroundColor.A), sender.Control.BackgroundColor.B, color.B) },
                {0, 1,  new Animation(v => sender.Control.BackgroundColor = new Color(sender.Control.BackgroundColor.R, sender.Control.BackgroundColor.G, sender.Control.BackgroundColor.B, v), sender.Control.BackgroundColor.A, color.A) },
            }.Commit(sender.Control, ChangeBackgroundColorAnimationName, 16, (uint)duration, easing, (d, b) => animationCompletionSource.SetResult(true));
```
sender.Control is null so it'll fail.

**Comment by AndreiMisiukevich** [comment]
@MitchBomcanhao your are best QA haha)

**Comment by AndreiMisiukevich** [comment]
@MitchBomcanhao https://github.com/AndreiMisiukevich/TouchEffect/blob/master/TouchEffect/TouchVisualManager.cs#L343

Adding

if(sender.Control == null)
{
return Task.FromResult(false);
}

Should solve this issue.
Would you like to make extra PR (test it before please)

**Comment by MitchBomcanhao** [comment]
It still fails on the same spot.
goes up to:
![image](https://user-images.githubusercontent.com/31066938/59929653-36814900-9439-11e9-8e1f-393c43c84e39.png)
then fails
![image](https://user-images.githubusercontent.com/31066938/59929699-4d27a000-9439-11e9-96e3-71fef04997a7.png)


as you can see, the control isn't null up to the point where it awaits for the task to complete.

**Comment by AndreiMisiukevich** [comment]
@MitchBomcanhao got it, thanks

**Comment by AndreiMisiukevich** [comment]
Need to refactor code a little

**Comment by AndreiMisiukevich** [comment]
@MitchBomcanhao does it work?)

**Comment by MitchBomcanhao** [comment]
Yes, first impression is that it is working fine ;)
