### ISSUE TITLE
Effects not working

### ISSUE THREAD

**Issue by bohbra** [AndreiMisiukevich/TouchEffect#42]
I created a bare bones Xamarin Forms application that uses the `TouchColorViewPage.xaml` and it doesn't appear to be working.  The sample application does work for me however, not sure what the issue is.

Here is the fork:
https://github.com/bohbra/TouchEffect

**Comment by AndreiMisiukevich** [comment]
@bohbra so it works on forked repo but doesn't work on your sample?
Can you provide a sample? I believe you forget to add TouchEffectPreserver.Preserve() line to your AppDelegate and MainActivity

**Comment by AndreiMisiukevich** [comment]
Let me know if it helped (or provide a sample)

**Comment by bohbra** [comment]
I forgot to add it to MainActivity which I now fixed, but it was in AppDelegate.  Neither works.  The sample is in the forked repo under the solution folder `Issue`.

**Comment by AndreiMisiukevich** [comment]
@bohbra you forgot to add one important thing man))

![image](https://user-images.githubusercontent.com/10124814/75488427-5baf5980-59c1-11ea-8c6b-5757e45dcbb5.png)

**Comment by AndreiMisiukevich** [comment]
```xaml
<ContentView.Effects>
    <touch:TouchEff Completed="Handler" />
</ContentView.Effects>
```

**Comment by bohbra** [comment]
Got it, thank you!

**Comment by bohbra** [comment]
Is a handler always required?  I would like to do something like this since I don't have a need for it but it doesn't work:

```xaml
<ContentView.Effects>
    <touch:TouchEff />
</ContentView.Effects>
```

**Comment by AndreiMisiukevich** [comment]
> Is a handler always required? I would like to do something like this since I don't have a need for it but it doesn't work:
> 
> ```
> <ContentView.Effects>
>     <touch:TouchEff />
> </ContentView.Effects>
> ```

Hi, yes. Handler is required.
In another case how would you handle touches?

You should user Handler **OR** Command

**Comment by bohbra** [comment]
I'm only using these features:

```C#
TouchEff.PressedBackgroundColor
TouchEff.RegularBackgroundColor
TouchEff.Command
TouchEff.CommandParameter
```

I want to change the background color of a frame and also receive the touch event via the command.  I don't have a need for the handler in my case but I have to add an empty one or the `PressedBackgroundColor` won't work.

**Comment by AndreiMisiukevich** [comment]
> I'm only using these features:
> 
> ```cs
> TouchEff.PressedBackgroundColor
> TouchEff.RegularBackgroundColor
> TouchEff.Command
> TouchEff.CommandParameter
> ```
> 
> I want to change the background color of a frame and also receive the touch event via the command. I don't have a need for the handler in my case but I have to add an empty one or the `PressedBackgroundColor` won't work.

Checking it

**Comment by AndreiMisiukevich** [comment]
@bohbra 
```xaml
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:touch="clr-namespace:TouchEffect;assembly=TouchEffect"
             x:Class="TouchEffectSample.TouchColorViewPage"
             BackgroundColor="White"
             Title="TouchColorViewPage">
    <StackLayout>
        <ContentView Padding="10,5"
                     touch:TouchEff.Command="{Binding LoginCommand}"
                     touch:TouchEff.PressedBackgroundColor="Red"
                     touch:TouchEff.RegularBackgroundColor="Green"
                     HorizontalOptions="CenterAndExpand"
                     VerticalOptions="CenterAndExpand">
            <ContentView.Effects>
                <touch:TouchEff />
            </ContentView.Effects>

            <Label FontSize="60" Text="CLICK ME" TextColor="Black" />
        </ContentView>
    </StackLayout>
</ContentPage>
```

works fine
